#!/bin/sh

alias a='alias'
a _cd='builtin cd'
a c='clear'
a ls='ls -F'
a la='ls -A'
a ll='ls -l'
a mkdir='mkdir -p'
a x='exit'
a ..='cd ..'

# CMDs with "c" prefix
for i in e ls la ll; do
	a c"$i"="c; $i"
done

