#!/bin/sh
# shellcheck disable=SC2139
# vi: syntax=sh

alias c='clear'
alias ls='ls -F'
alias la='ls -A'
alias ll='ls -l'
alias mkdir='mkdir -p'
alias x='exit'
alias ..='cd ..'
alias python='env python3'
alias yaourt='yay'

##
# CMDs with "c" prefix
##
for i in         \
	e        \
	ls       \
	la       \
	ll       \
	uf       \
	nf       \
	fortune  \
	neofetch
do
	alias "c${i}=c; ${i}"
done

##
# CMDs that need root privileges
##

# Linux / FreeBSD
for i in           \
	apt        \
	apt-get    \
	pacman     \
	portmaster \
	yum        \
	dnf        \
	pkg        \
	brew       \
	eopkg      \
	wifi-menu
do
	[ -x "$(command -v "$i")" ] && alias "${i}='sudo ${i}'"
done

# OpenBSD
for i in \
	pkg_add    \
	pkg_delete
do
	[ -x "$(command -v "$i")" ] && alias "${i}='doas ${i}'"
done

