#!/bin/sh

~/bin/log "Setting up directory structure..."

link_from_to() { # $1:fromFile $2:toFile
	[ -f $1 ] || [ -d $1 ] || return 1
	[ ! -L $2 ] || return 1
	[ -f $2 ] && mv $2 ${2}.old
	ln -sf $1 $2 && ~/bin/log "$1 linked to $2"
}

# create symlinks if missing
link_from_to ~/etc/kshrc ~/.kshrc
link_from_to ~/etc/kshrc ~/.mkshrc
link_from_to ~/etc/vimrc ~/.vimrc
link_from_to ~/etc/vim ~/.vim
link_from_to ~/etc/Xresources ~/.Xresources

# make my dirs
for DIR in src var uni tmp; do
	[ -d "$HOME/$DIR" ] && continue
	mkdir -p "$HOME/$DIR"
	~/bin/log "$HOME/$DIR not found, directory added"
done

# add my bin launchers
[ -d ~/bin/launchers ] && [ -d ~/.local/share/applications ] && for APP in ~/bin/launchers/*.desktop; do
	LAUNCHER="$HOME/.local/share/applications/$(basename "$APP")"
	[ ! -L "$LAUNCHER" ] && ln -sf "$APP" "$LAUNCHER"
	~/bin/log "$APP luncher installed"
done

