#!/bin/sh
# https://gitlab.com/morgaux/etc

##
# dwm wrapper to launch dwm and set the status etc.
##

#symlink to /usr/local/bin/dwm-start:
#ln -sf ~/etc/dwm-start /usr/local/bin/dwm-start

#black bg
xsetroot -solid black

#while loop to update statusbar
while true; do

	#battery
	battper="$(acpi | awk '{print $4}' | tr -d ',')";
	battery="$(acpi | awk '{print $3}' | tr -d ',')";

	#time
	CLK=$( date +'%a %b %d %R:%S %Z' )

	#volume
	if [ "$(amixer get Master | tail -1 | awk '{print $6}' | tr -d '[]')" = "on" ] ; then 
		# volume % with leading space for padding if <10%
		VOL="$(printf "%3s" "$(amixer get Master | tail -1 | awk '{ print $5 }' | tr -d '[]')")"
	else
		VOL="(X)" # mute symbol
	fi

	#put it in the xsetrootname
	xsetroot -name " [ $battper - $battery ] [ Vol: $VOL ] [ $CLK ] "

	sleep 1
done &

sleep 1

/usr/bin/nm-applet &

# set wallpaper
feh -z -Z --bg-scale /home/morgaux/var/Pictures/Wallpapers/castle.png

exec /usr/local/bin/dwm > /dev/null

