#!/bin/sh

# set PATH so it includes user's private bin
if [ -d "$HOME/bin" ] ; then
	PATH="$HOME/bin:$PATH"
fi

# set EDITOR to most prefered available
for i in vim vi nano ; do
	[ -x "$(command -v $i)" ] || continue
	EDITOR="$(which $i)"
	break
done

JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:/bin/javac::")
JUNIT_HOME="$HOME/uni/159272/lib/junit5"
CLASSPATH="$CLASSPATH:.:$JUNIT_HOME:$JUNIT_HOME/junit4.10"

# export variables
export PATH && log "Path: $PATH"
export HOME && log "Home: $HOME"
export EDITOR && log "Editor: $EDITOR"
export JUNIT_HOME && log "JUnit: $JUNIT_HOME"
export JAVA_HOME && log "Java: $JAVA_HOME"
export CLASSPATH && log "Classpath: $CLASSPATH"

