#!/bin/sh

#[ PATH ]#######################################################################

# set PATH
for dir in	"/sbin" \
		"/bin" \
		"/usr/sbin" \
		"/usr/bin" \
		"/usr/local/sbin" \
		"/usr/local/bin" \
		"$HOME/bin" \
		"$HOME/src/ufetch"
do
	if [ -d "$dir" ]
	then
		PATH="$dir:$PATH"
	fi
done

# set os specific bin
case "$(uname -a)" in
	*"FreeBSD"*)
		[ -d "$HOME/bin/freebsd" ] && PATH="$HOME/bin/freebsd:$PATH" ;;
	*"OpenBSD"*)
		[ -d "$HOME/bin/openbsd" ] && PATH="$HOME/bin/openbsd:$PATH" ;;
esac

# remove path duplicates
export PATH=$(printf "%s" "$PATH" | \
	awk -v RS=':' '!a[$1]++ { if (NR > 1) printf RS; printf $1 }')

#[ MISC ]#######################################################################

# set EDITOR to most preferred available
export EDITOR="$(which vim || which vi)"

# set PAGER
export PAGER=less

# set ENV to local kshrc, possibly overrides symlinks
export ENV="$HOME/etc/kshrc"

#[ DEV ]########################################################################

# set JAVA variables if java is installed
if [ -x "$(command -v javac)" ] || [ -x "$(command -v java)" ]
then
	export JAVA_HOME="$(readlink -f /usr/bin/javac | sed 's:/bin/javac::')"
	export CLASSPATH="$CLASSPATH:."

	# for DWM and other tilling wms
	export _JAVA_AWT_WM_NONREPARENTING="1"
fi

export DOTNET_CLI_TELEMETRY_OPTOUT=1

# set DVTM_TERM for compatibility
if [ -x "$(command -v dvtm)" ]
then
	export DVTM_TERM="xterm"
fi

################################################################################

