#!/bin/sh

export _GIT_NAME="Morgaux"
export _GIT_EMAIL="3158796-morgaux@users.noreply.gitlab.com"

if [ -x "$(command -v git)" ]
then

	[ -z "$(git config user.name)" ] && \
		git config --global user.name "${_GIT_NAME}"

	[ -z "$(git config user.email)" ] && \
		git config --global user.email "${_GIT_EMAIL}"

	git config --global credential.helper cache 86400

fi

