#!/bin/sh

#
# http://gitlab.com/morgaux/etc
#

# ~/.profile generator

set -e

echo "#!/bin/sh" > ~/.profile.tmp
echo "" >> ~/.profile.tmp
echo "##                                                                           ##" >> ~/.profile.tmp
echo "#                              !!! IMPORTANT !!!                              #" >> ~/.profile.tmp
echo "#                                                                             #" >> ~/.profile.tmp
echo "#               DO NOT MODIFY - FILE GENERATED BY ~/etc/profile               #" >> ~/.profile.tmp
echo "#                                                                             #" >> ~/.profile.tmp
echo "##                                                                           ##" >> ~/.profile.tmp
echo "" >> ~/.profile.tmp

for file in aliases directory environment; do
	cat ~/etc/$file >> ~/.profile.tmp || exit 1 # create temporary file
done

rm ~/.profile

mv ~/.profile.tmp ~/.profile

# if xbanish exists and is not yet running, run it in background
hasX && \
	[ -x "$(command -v xbanish)" ] && \
	[ "$(ps -a | grep xbanish)" = "" ] && \
	{ xbanish & }

