#!/bin/sh

#
# http://gitlab.com/morgaux/etc
#

##
# ~/.profile generator
##

set -e # stop on uncaught error

~/bin/log "Generating ~/.profile..."

##
# Warning message
##
{
	echo '#!/bin/sh'
	echo ''
	echo '##                                                                           ##'
	echo '#                              !!! IMPORTANT !!!                              #'
	echo '#                                                                             #'
	echo '#               DO NOT MODIFY - FILE GENERATED BY ~/etc/profile               #'
	echo '#                                                                             #'
	echo '##                                                                           ##'
	echo ''
	echo '~/bin/log "Running ~/.profile"'
	echo '~/bin/log "Uptime: $(uptime)"'
	echo '~/bin/log "Machine: $(uname -sm)"'
} > ~/.profile.tmp # Create new temporary file

##
# add environment setup scripts to temporary file
##
for file in startup environment directory aliases; do
	sed -n '/#!\/bin/!p' ~/etc/$file >> ~/.profile.tmp || exit 1
done

##
# replace old file
##
cat ~/.profile > ~/.profile.bak || true
rm ~/.profile || ~/bin/log "Error occured in removing file"

awk '{if ($0 ~ /\/bin\/log/) {print $0 " || true"} else {print $0}}' \
	< ~/.profile.tmp \
	> ~/.profile || ~/bin/log "Error occured in moving file"

rm -f ~/.profile.tmp || ~/bin/log "Error in removing file"

exit 0

