#!/bin/sh

# if command exists and is not yet running, run it in background
run_one_instance_in_bg() {
	if [ -x "$(command -v "$1")" ] && pgrep "$1"
	then
		# shellcheck disable=2068
		( $@ &)
	fi
}


#
# Start ups that require Xorg
#

if [ -n "$DISPLAY" ] && xset q >/dev/null 2>&1
then

	run_one_instance_in_bg "xbanish"
	run_one_instance_in_bg "redshift"

fi >/dev/null 2>&1 # hide error stream for the if...fi block


#
# Keep repos up to date - spawn "git pull" daemons
#

if [ -x "$(command -v git)" ]
then

	# function to safely pull git repos
	git_pull_dir() { ( cd "$1" && git pull </dev/null >/dev/null 2>&1 & ) ; }

	# pull git repos in home
	for i in "$HOME/bin" "$HOME/etc"
	do
		git_pull_dir "$i"
	done

	# pull git repos in ~/src and ~/uni
	( cd "$HOME/src" && for i in ./* ; do git_pull_dir "$i"; done; )
	( cd "$HOME/uni" && for i in ./* ; do git_pull_dir "$i"; done; )

	# commit spelling changes to vim spelling files
	( cd "$HOME/etc" && git commit -m "Automatic spelling commit" vim/spell/* )

fi </dev/null >/dev/null 2>&1 # block all io streams for the if...fi block

