#!/bin/sh

# Start ups that require Xorg
if [ -n "$DISPLAY" ] && xset q >/dev/null 2>&1
then
	# if xbanish exists and is not yet running, run it in background
	if [ -x "$(command -v xbanish)" ] && \
		[ "$(ps cax | grep xbanish)" = "" ]
	then
		( xbanish & )
	fi

	if [ -x "$(command -v redshift)" ] && \
		[ "$(ps cax | grep redshift)" = "" ]
	then
		( redshift -t 6500k:4000k >/dev/null 2>&1 & )
	fi
fi >/dev/null 2>&1

git_pull_dir() { ( cd "$1" && git pull </dev/null >/dev/null 2>&1 & ) ; }

if [ -x "$(command -v git)" ]
then
	for i in "$HOME/bin" "$HOME/etc"
	do
		git_pull_dir "$i"
	done

	( cd "$HOME/src" && for i in ./* ; do git_pull_dir "$i"; done; )
	( cd "$HOME/uni" && for i in ./* ; do git_pull_dir "$i"; done; )
fi </dev/null >/dev/null 2>&1

