#!/bin/sh

~/bin/log "Launching startup applications..."

# Start ups that require Xorg
if hasX ; then
	# if xbanish exists and is not yet running, run it in background
	[ -x "$(command -v xbanish)" ] && if [ "$(ps cax | grep xbanish)" = "" ] ; then
		~/bin/log "xbanish started"
		xbanish &
	else
		~/bin/log "xbanish already running"
	fi
	[ -x "$(command -v redshift)" ] && if [ "$(ps cax | grep redshift)" = "" ] ; then
		redshift -t 6500k:4000k & >/dev/null 2>&1
	fi
fi

