#!/bin/sh

# ~/etc/vim-plugins {{{

#
# Auto git cloner for vim plugins
#

# Retry if offline {{{
if ! ping -q -w 1 -c 1 8.8.8.8 >/dev/null 2>&1
then
	#echo "host is offline, cannot check vim plugins" 1>&2

	(sleep 5 && exec "$0" &) &

	exit 1
fi
# Retry if offline }}}

# Config {{{
BUNDLE_DIR="$HOME/etc/vim/bundle"
AUTOLOAD_DIR="$HOME/etc/vim/autoload"
PATHOGEN_URL="https://tpo.pe/pathogen.vim"
# Config }}}

# Start up validation {{{
if [ ! -d "$BUNDLE_DIR" ]
then
	mkdir -p "$BUNDLE_DIR"
fi

if [ ! -d "$AUTOLOAD_DIR" ]
then
	mkdir -p "$AUTOLOAD_DIR"
fi

if [ ! -x "$(command -v git)" ]
then
	echo "git is not installed" 1>&2
	exit 1
fi

if [ ! -x "$(command -v curl)" ]
then
	echo "curl is not installed" 1>&2
	exit 1
fi

if ! curl -LSso "${AUTOLOAD_DIR}/pathogen.vim" "$PATHOGEN_URL"
then
	echo "Could not install ${PATHOGEN_URL}" 1>&2
fi
# Start up validation }}}

# Function to clone a repo to a directory, or pull if the directory exists {{{
clone_or_pull() { # $1:url $2:destdir
	if ! git ls-remote "$1" 1>/dev/null 2>&1
	then
		echo "$1 is an invalid repo url" 1>&2
		exit 1
	fi

	if [ ! -d "$2" ]
	then
		mkdir -p "$2"
	fi

	_PREV_DIR="$(pwd)"
	cd "$2"

	if [ -d "$(basename "$1")" ]
	then
		cd "$(basename "$1")"

		echo "Updating ${1}..."

		if ! git pull 1>/dev/null 2>&1
		then
			echo "git pull $1 failed" 1>&2
			exit 1
		fi
	else
		echo "Installing ${1}..."

		if ! git clone "$1" 1>/dev/null 2>&1
		then
			echo "git clone $1 failed" 1>&2
			exit 1
		fi
	fi

	cd "$_PREV_DIR"
}
# Function to clone a repo to a directory, or pull if the directory exists }}}

# Main loop, run through all plugin repositories listed {{{
for file in "${BUNDLE_DIR}/.plugins.github" "${BUNDLE_DIR}/.plugins.gitlab"
do
	if [ ! -f "$file" ]
	then
		echo "$file doesn't exist, skipping..." 1>&2
		continue
	fi

	case "$(echo "$file" | sed 's/.*\.//g')" in
		"github")
			for line in $(tr '\n' ' ' < "$file")
			do
				clone_or_pull "https://github.com/${line}" "$BUNDLE_DIR"
			done
			;;
		"gitlab")
			for line in $(tr '\n' ' ' < "$file")
			do
				clone_or_pull "https://gitlab.com/${line}" "$BUNDLE_DIR"
			done
			;;
		*)
			echo "unreachable"
			exit 1
			;;
	esac
done
# Main loop, run through all plugin repositories listed }}}

# ~/etc/vim-plugins }}}

