#!/bin/sh

export WALLPAPER=""

if [ -x "$(command -v setfont)" ] && [ "$TERM" = "linux" ]
then
	# set console font
	setfont Lat2-Terminus16
fi

if [ -n "$DISPLAY" ]
then
	xrdb -merge ~/etc/Xresources
fi

