#!/bin/sh

[ -x "$(command -v xdg-user-dirs-update)" ] || exit 1

for i in Desktop Documents Downloads Music Pictures Public Templates Videos; do
	mkdir -p "$HOME/var/$i"
	[ -d "$HOME/$i" ] && mv "$HOME/$i/*" "$HOME/var/$i/."
	[ -z "$(ls -A "$HOME/$i" 2>/dev/null)" ] && rm -rf "${HOME:?}/$i"
done

xdg-user-dirs-update --set DESKTOP ~/var/Desktop
xdg-user-dirs-update --set DOCUMENTS ~/var/Documents
xdg-user-dirs-update --set DOWNLOAD ~/var/Downloads
xdg-user-dirs-update --set MUSIC ~/var/Music
xdg-user-dirs-update --set PICTURES ~/var/Pictures
xdg-user-dirs-update --set PUBLICSHARE ~/var/Public
xdg-user-dirs-update --set TEMPLATES ~/var/Templates
xdg-user-dirs-update --set VIDEOS ~/var/Videos

xdg-user-dirs-update

