"
" https://gitlab.com/morgaux/etc
" Author:   Morgaux Meyer
" License:  MIT (C) Morgaux Meyer
"

" enable syntax
syntax on

" misc options
set belloff=all
set showcmd
set nohlsearch
set nu
set ruler
set report=1
set nowrap
set nocompatible
set showtabline=2
set laststatus=2
set ignorecase
set spell spelllang=en_nz
set autoindent

" Tabs must be eight wide!!!
set tabstop=8 softtabstop=0 shiftwidth=8 noexpandtab

" Override language specific settings
autocmd Filetype python setlocal tabstop=8 softtabstop=0 shiftwidth=8 noexpandtab
autocmd Filetype scala  setlocal tabstop=8 softtabstop=0 shiftwidth=8 noexpandtab
autocmd Filetype java   setlocal tabstop=8 softtabstop=0 shiftwidth=8 noexpandtab

" auto make latex on save
autocmd BufWritePost *.tex silent !make >/dev/null

" No line numbers if the term is too narrow for 80 chars
if &columns < 85
	set nonu
endif

" Colours and highlighting
set t_Co=256
set t_ut=""
set background=dark           " ahhhhhh my eyes!!
set t_8f=[38;2;%lu;%lu;%lum " set foreground color
set t_8b=[48;2;%lu;%lu;%lum " set background color
set t_Co=256                  " Enable 256 colors
set termguicolors             " Enable GUI colors for the terminal to get truecolor
colo sourcerer

" prevent annoying paren matching
let loaded_matchparen = 1

" Catch whitespace errors
match Error /\s\+$\| \+\ze\t/
au InsertEnter * redraw!
au InsertLeave * redraw!

" Show tabs as comments
set list
set listchars=tab:\|\ 
match Comment /\t/


"
" I've shamelessly stolen this stuff, although it's quite good so I don't mind
"
" http://github.com/jcs/dotfiles
" Author: Joshua Stein
" License: none
"
" Don't pollute directories with swap files, keep them in one place
silent !mkdir -p ~/.vim/backup/
silent !mkdir -p ~/.vim/swp/
set backupdir=~/.vim/backup//
set directory=~/.vim/swp//
" ...except crontab, which will complain that it can't see any changes
au FileType crontab setlocal bkc=yes

