# Shell variables
# Generated by 'wal'
wallpaper='/home/morgaux/zK0Fmba.jpg'

# Special
background='#0C0201'
foreground='#cae4d9'
cursor='#cae4d9'

# Colors
color0='#0C0201'
color1='#B45344'
color2='#936858'
color3='#CA5B4B'
color4='#D4614F'
color5='#898C7A'
color6='#C9D4BA'
color7='#cae4d9'
color8='#8d9f97'
color9='#B45344'
color10='#936858'
color11='#CA5B4B'
color12='#D4614F'
color13='#898C7A'
color14='#C9D4BA'
color15='#cae4d9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
