--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/usr/share/backgrounds/dwm-wallpaper"

-- Special
background="#0f1213"
foreground="#ccdce4"
cursor="#ccdce4"

-- Colors
color0="#0f1213"
color1="#566B73"
color2="#9C7863"
color3="#5A7988"
color4="#6F8E9C"
color5="#8AA3AE"
color6="#A9C3D1"
color7="#ccdce4"
color8="#8e9a9f"
color9="#566B73"
color10="#9C7863"
color11="#5A7988"
color12="#6F8E9C"
color13="#8AA3AE"
color14="#A9C3D1"
color15="#ccdce4"
