--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/morgaux/zK0Fmba.jpg"

-- Special
background="#0C0201"
foreground="#cae4d9"
cursor="#cae4d9"

-- Colors
color0="#0C0201"
color1="#B45344"
color2="#936858"
color3="#CA5B4B"
color4="#D4614F"
color5="#898C7A"
color6="#C9D4BA"
color7="#cae4d9"
color8="#8d9f97"
color9="#B45344"
color10="#936858"
color11="#CA5B4B"
color12="#D4614F"
color13="#898C7A"
color14="#C9D4BA"
color15="#cae4d9"
