# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/backgrounds/dwm-wallpaper'

# Special
background='#0f1213'
foreground='#ccdce4'
cursor='#ccdce4'

# Colors
color0='#0f1213'
color1='#566B73'
color2='#9C7863'
color3='#5A7988'
color4='#6F8E9C'
color5='#8AA3AE'
color6='#A9C3D1'
color7='#ccdce4'
color8='#8e9a9f'
color9='#566B73'
color10='#9C7863'
color11='#5A7988'
color12='#6F8E9C'
color13='#8AA3AE'
color14='#A9C3D1'
color15='#ccdce4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
