#!/bin/sh

# Helper function to manage symlinks {{{
link_from_to() { # $1:fromFile $2:toFile
	[   -f "$1" ] ||
	[   -d "$1" ] ||
		return 1 # fromFile doesn't exist

	[ ! -L "$2" ] || # toFile is already a link
		return 1

	[   -f "$2" ] && # if toFile exists
		mv "$2" "${2}.old" # make a back up of toFile

	ln -sf "$1" "$2" # link files
}
# Helper function to manage symlinks }}}

# Ensure directories exist {{{
for DIR in             \
	"src"          \
	"var"          \
	"var/books"    \
	"uni"          \
	"tmp"          \
	".cache"       \
	"$DOTNET_ROOT"
do
	[ -d "${HOME}/${DIR}" ] || mkdir -p "${HOME}/${DIR}"
done
# Ensure directories exist }}}

# Install Books {{{
# Loop var BOOK is a string in the form:
# 	<URL> | <FILENAME>
# where URL is a link at which the book can be downloaded from and FILENAME is
# the file name the book should the saved as in the ~/var/books directory. Note
# that FILENAME may contain a "/" to denote subdirectories but not "|" as this
# is the delimiter character.
for BOOK in \
	'https://www.gutenberg.org/files/2488/2488-8.txt|20000_Leagues_Under_the_Seas.txt'   \
	'https://www.gutenberg.org/cache/epub/103/pg103.txt|Around_the_World_in_80_days.txt' \
	'https://www.gutenberg.org/files/132/132-0.txt|The_Art_of_War.txt'                   \
	'https://www.gutenberg.org/cache/epub/1004/pg1004.txt|The_Divine_Comedy.txt'
do
	URL="$(echo "$BOOK" | awk -F '|' '{ print $1 }')"
	FILENAME="${HOME}/var/books/$(echo "$BOOK" | awk -F '|' '{ print $2 }')"

	# proceed if book not yet downloaded
	if [ -f "${FILENAME}" ]
	then
		continue
	fi

	# download using curl or wget
	if [ -x "$(command -v curl)" ]
	then
		curl -s -S -o "${FILENAME}" "${URL}"
	elif [ -x "$(command -v wget)" ]
	then
		wget -q -O "${FILENAME}" "${URL}"
	fi
done
# Install Books }}}

# Symlink dotfiles to the HOME directory {{{
link_from_to ~/etc/aliases    ~/.aliases
link_from_to ~/etc/fvwmrc     ~/.fvwmrc
link_from_to ~/etc/kshrc      ~/.kshrc
link_from_to ~/etc/kshrc      ~/.mkshrc
link_from_to ~/etc/vim/vimrc  ~/.vimrc
link_from_to ~/etc/vim        ~/.vim
link_from_to ~/etc/Xresources ~/.Xresources
link_from_to ~/etc/Xresources ~/.Xdefaults
link_from_to ~/etc/xinitrc    ~/.xinitrc
link_from_to ~/etc/xinitrc    ~/.xsession
link_from_to ~/etc/wal        ~/.cache/wal
# Symlink dotfiles to the HOME directory }}}

# Make sure these dotfiles are executable {{{
for i in ~/.kshrc ~/.mkshrc ~/.xinitrc ~/.xsession
do
	[ -x "$i" ] || chmod 755 "$i"
done
# Make sure these dotfiles are executable }}}

