#!/bin/sh

# ~/etc/setup/git-config {{{

export _GIT_NAME="Morgaux"
export _GIT_EMAIL="3158796-morgaux@users.noreply.gitlab.com"

if [ -x "$(command -v git)" ]
then
	if [ -z "$(git config user.name)" ]
	then
		git config --global user.name "${_GIT_NAME}"
	fi

	if [ -z "$(git config user.email)" ]
	then
		git config --global user.email "${_GIT_EMAIL}"
	fi

	git config --global credential.helper cache 86400
fi

# ~/etc/setup/git-config }}}

