#!/bin/sh

# run command singleton in background
run_one_instance_in_bg() {
	# shellcheck disable=SC2009
	if [ -x "$(command -v "$1")" ]
	then
		# shellcheck disable=2068
		ps cax | grep -iq "$1" || ( sh -c $@ &)
	fi
}

if [ -n "$DISPLAY" ] && xset q >/dev/null 2>&1
then
	run_one_instance_in_bg "xbanish"
	run_one_instance_in_bg "redshift"

	xrdb "$HOME/.Xresources"
fi >/dev/null 2>&1 # hide error stream for the if...fi block

