#!/bin/sh

# run command singleton in background
run_one_instance_in_bg() {
	# shellcheck disable=SC2009
	if [ -x "$(command -v "$1")" ]
	then
		# shellcheck disable=2068
		ps cax | grep -iq "$1" || ( sh -c $@ &)
	fi
}

if [ -x "$(command -v sudo)"                ] &&
   [ -x "$(command -v pacman)"              ] &&
   [ -x "$(command -v "$(sudo -l pacman)")" ]
then
	#
	# Clear the package cache
	#
	# When I set up my arch-box, I was way to conservative on my
	# partitioning scheme and so while my /home has plenty of space,
	# running `pacman -Syu` often fails due to /var getting filled up
	# with cached package versions, which I don't care about.
	#
	(yes | sudo pacman -Sccq >/dev/null 2>&1 &)
fi

if [ -n "$DISPLAY" ] && xset q >/dev/null 2>&1
then
	run_one_instance_in_bg "xbanish"
	run_one_instance_in_bg "redshift"

	xrdb "$HOME/.Xresources"
fi >/dev/null 2>&1 # hide error stream for the if...fi block

