#!/bin/sh

# ~/etc/setup/welcome {{{

# Check last login time {{{
_LAST_LOGIN_FILE="${HOME}/.logintimestamp"
touch "${_LAST_LOGIN_FILE}"
# Check last login time }}}

# Manage UNIX style configurations {{{
export WALLPAPER=""

if [ -x "$(command -v setfont)" ] && [ "$TERM" = "linux" ]
then
	# set console font
	setfont Lat2-Terminus16
fi

if [ -n "$DISPLAY" ]
then
	xrdb -merge ~/etc/Xresources
fi
# Manage UNIX style configurations }}}

# Run ASCII welcome if first login in past hour {{{
if [ "$(($(date +%s) - 3600))" -gt "$(head -n 1 "${_LAST_LOGIN_FILE}")" ]
then
	[ -x "$(command -v uf)" ] && uf # run ufetch
fi
# Run ASCII welcome if first login in past hour }}}

# Update last login time {{{
date +%s > "${_LAST_LOGIN_FILE}" # UNIX timestamp format
# Update last login time }}}

# ~/etc/setup/welcome }}}

